<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GoXlrControl.Hardware</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsonPatch.Net" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoXlrControl.Hardware.Abstractions\GoXlrControl.Hardware.Abstractions.csproj" />
  </ItemGroup>
</Project>
